name: ci-java-workflow
on: [push]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build com Maven
        run: mvn -B package --file pom.xml
      - name: Executar testes
        run: mvn test --file pom.xml